#+TITLE: ANNAPL
#+AUTHOR: John Thingstad
#+DATE: <2023-08-02 on.>
#+OPTIONS: author:nil

#+hugo_base_dir: ~/Dokumenter/April
#+hugo_selection: posts
#+hugo_front_matter_format: yaml

* Artificial Neural Nets in APL

[ANNAPL](https://github.com/rodrigogiraoserrao/ANNAPL) is a github cite with a example
neural net implementation in APL. In particular notice mnistdata.rar which is the
handwritten character data in 128x128 pixel gray-format encoded as a compressed CSV file.
I will need this data as the original data cite
[yann.lecun.com](https://yann.lecun.com/exdb/mnist/) is now password protected. Not sure
why, but I suspect the traffic given the recent influx in DNN's has become to great for
his server to handle.

His code uses :For :InEach several times. This is not implemented in April. I will try to
use the nest (⍣) operator instead. f⍣5 x ⟹ f(f(f(f(f x)))) so actionFn∘_F⍣≢layers or
something along those lines.

# Local Variables:
# eval: (set-fill-column 90)
# eval: (auto-fill-mode t)
# eval: (org-hugo-auto-export-mode t)
# End:

#  LocalWords:  SPIR Vulkan GPUs Juuso ANNAPL CSV mnistdata rar InEach actionFn
